<?php
declare(strict_types=1);

namespace App\Core;

/**
 * Installer: writes config.php and seeds baseline data (locations, users,
 * settings, scrape targets). Used by both the web installer (install.php) and
 * the headless CLI installer (scripts/install_cli.php). All seeds idempotent.
 */
class Installer
{
    public static function isInstalled(): bool
    {
        return is_file(APP_ROOT . '/config.php');
    }

    /** Write config.php from $v. Generates SESSION_SECRET. Returns the path. */
    public static function writeConfig(array $v): string
    {
        $esc = static fn($s): string => str_replace(['\\', "'"], ['\\\\', "\\'"], (string) $s);
        $lines = ['<?php'];
        $lines[] = '// Generated by the installer on ' . gmdate('Y-m-d H:i:s') . ' UTC. Do NOT commit.';
        $lines[] = 'declare(strict_types=1);';
        $lines[] = '';

        $str = static fn(string $k, $val) => "define('$k', '" . $esc($val) . "');";
        $raw = static fn(string $k, $val) => "define('$k', $val);";

        $lines[] = $str('APP_ENV', $v['app_env'] ?? 'production');
        $lines[] = $str('APP_URL', $v['app_url'] ?? 'http://localhost:8000');
        $lines[] = $str('APP_TIMEZONE', $v['timezone'] ?? 'America/Vancouver');
        $lines[] = '';
        $lines[] = $str('DB_HOST', $v['db_host'] ?? 'localhost');
        $lines[] = $raw('DB_PORT', (int) ($v['db_port'] ?? 3306));
        $lines[] = $str('DB_NAME', $v['db_name'] ?? '');
        $lines[] = $str('DB_USER', $v['db_user'] ?? '');
        $lines[] = $str('DB_PASS', $v['db_pass'] ?? '');
        $lines[] = '';
        $lines[] = $str('SESSION_SECRET', bin2hex(random_bytes(32)));
        $lines[] = $str('SESSION_NAME', 'cdd_session');
        $lines[] = '';
        $lines[] = $str('ANTHROPIC_API_KEY', $v['anthropic_key'] ?? '');
        $lines[] = $str('ANTHROPIC_API_URL', 'https://api.anthropic.com/v1/messages');
        $lines[] = $str('ANTHROPIC_VERSION', '2023-06-01');
        $lines[] = $str('ANTHROPIC_MODEL_FAST', $v['model_fast'] ?? 'claude-haiku-4-5');
        $lines[] = $str('ANTHROPIC_MODEL_SMART', $v['model_smart'] ?? 'claude-sonnet-4-6');
        $lines[] = $raw('ANTHROPIC_MONTHLY_BUDGET_USD', 50);
        $lines[] = '';
        $lines[] = $str('SCRAPE_USER_AGENT', $v['scrape_ua'] ?? 'CrossroadsDD/1.0 (+mailto:josh@swens.net)');
        $lines[] = $raw('SCRAPE_MIN_DELAY_SECONDS', 5);
        $lines[] = $str('CROSSROADS_HOME_STORE', $v['home_store'] ?? 'crossroads');
        $lines[] = '';
        $lines[] = $raw('BACKUP_DIR', "__DIR__ . '/storage/backups'");
        $lines[] = $raw('BACKUP_RETENTION_DAYS', 30);
        $lines[] = $str('BACKUP_SECONDARY_DIR', $v['backup_secondary'] ?? '');
        $lines[] = $str('MYSQLDUMP_BIN', $v['mysqldump_bin'] ?? 'mysqldump');
        $lines[] = '';
        $lines[] = $str('MAIL_FROM', $v['mail_from'] ?? 'dd@crossroadscannabis.ca');
        $lines[] = $str('MAIL_OWNER', $v['owner_email'] ?? 'josh@swens.net');
        $content = implode("\n", $lines) . "\n";

        file_put_contents(APP_ROOT . '/config.php', $content, LOCK_EX);
        return APP_ROOT . '/config.php';
    }

    /** Seed locations, users, settings. Idempotent. */
    public static function seed(array $owner, array $purchaser = []): void
    {
        self::upsertLocation('burns-lake', 'Burns Lake', 1, null, 'crossroads');
        self::upsertLocation('penticton', 'Penticton', 0, '2026-06-30', null);

        self::upsertUser((string) $owner['email'], (string) ($owner['name'] ?? 'Owner'), 'owner', (string) $owner['password']);
        if (!empty($purchaser['email'])) {
            self::upsertUser((string) $purchaser['email'], (string) ($purchaser['name'] ?? 'Purchaser'), 'purchaser', (string) $purchaser['password']);
        }

        $defaults = [
            'app_name'                    => 'Crossroads DD Intelligence',
            'doh_target_days'             => '21',
            'dd_share_baseline'           => '0',
            'vape_illicit_benchmark'      => '',
            'movement_alert_threshold_pct' => '0.10',
            'benchmark_competitor'        => 'mojo',
        ];
        foreach ($defaults as $k => $val) {
            Database::query(
                "INSERT INTO settings (`key`, `value`) VALUES (?, ?)
                 ON DUPLICATE KEY UPDATE `key` = `key`",
                [$k, $val]
            );
        }

        // Scrape targets + their ci_stores rows (the proven blaze-scraper set).
        self::seedTargets(self::defaultTargets());
    }

    /**
     * Canonical scrape-target set: Crossroads home store + 4 competitors, with
     * the exact identifiers from the existing blaze-scraper (all Tymber menus
     * fetched through the Blaze ECOM endpoint via x-group/x-store headers).
     */
    public static function defaultTargets(): array
    {
        $blaze = 'https://ecom-api.blaze.me/api/v1/products';
        return [
            ['name' => 'crossroads',  'platform' => 'tymber', 'api_url' => $blaze, 'x_group' => '353c786f-2a89-425b-8ac2-e34371332868', 'x_store' => '353c786f-2a89-425b-8ac2-e34371332868', 'is_home' => 1],
            ['name' => 'mojo',        'platform' => 'tymber', 'api_url' => $blaze, 'x_group' => 'd7aced12-b380-4eb4-b278-ee1aa228c316', 'x_store' => 'd7aced12-b380-4eb4-b278-ee1aa228c316'],
            ['name' => 'rural-leaf',  'platform' => 'tymber', 'api_url' => $blaze, 'x_group' => '31faf394-2fae-46f1-888c-ecb62c8bb068', 'x_store' => '31faf394-2fae-46f1-888c-ecb62c8bb068'],
            ['name' => 'mjb',         'platform' => 'tymber', 'api_url' => $blaze, 'x_group' => 'ab776fac-2779-4438-9bb1-8607ccdb4353', 'x_store' => 'ab776fac-2779-4438-9bb1-8607ccdb4353'],
            ['name' => 'grasshopper', 'platform' => 'tymber', 'api_url' => $blaze, 'x_group' => '881541bb-5b5c-49bc-b913-a7cf37a4d3f5', 'x_store' => '881541bb-5b5c-49bc-b913-a7cf37a4d3f5'],
        ];
    }

    private static function upsertLocation(string $code, string $name, int $active, ?string $opensOn, ?string $ciStore): void
    {
        Database::query(
            "INSERT INTO locations (code, name, active, opens_on, ci_store_name)
             VALUES (?, ?, ?, ?, ?)
             ON DUPLICATE KEY UPDATE name = VALUES(name), active = VALUES(active),
               opens_on = VALUES(opens_on), ci_store_name = VALUES(ci_store_name)",
            [$code, $name, $active, $opensOn, $ciStore]
        );
    }

    public static function upsertUser(string $email, string $name, string $role, string $password): void
    {
        $email = strtolower(trim($email));
        $existing = Database::fetch("SELECT id FROM users WHERE email = ?", [$email]);
        if ($existing) {
            Database::query(
                "UPDATE users SET name = ?, role = ?, password_hash = ?, active = 1 WHERE id = ?",
                [$name, $role, Auth::hash($password), (int) $existing['id']]
            );
        } else {
            Database::query(
                "INSERT INTO users (email, name, role, password_hash) VALUES (?, ?, ?, ?)",
                [$email, $name, $role, Auth::hash($password)]
            );
        }
    }

    /**
     * Seed/refresh scrape targets + their ci_stores rows.
     * Each $targets entry: name, platform, api_url, x_group, x_store, x_app_mode, is_home, url.
     * Idempotent (keyed on unique store name).
     */
    public static function seedTargets(array $targets): void
    {
        foreach ($targets as $t) {
            $home = !empty($t['is_home']) ? 1 : 0;
            Database::query(
                "INSERT INTO dd_scrape_targets (store_name, url, platform, x_group, x_store, x_app_mode, is_home, active)
                 VALUES (:name, :url, :platform, :xg, :xs, :mode, :home, 1)
                 ON DUPLICATE KEY UPDATE url=VALUES(url), platform=VALUES(platform),
                   x_group=VALUES(x_group), x_store=VALUES(x_store), x_app_mode=VALUES(x_app_mode), is_home=VALUES(is_home)",
                [
                    'name' => $t['name'], 'url' => $t['url'] ?? '', 'platform' => $t['platform'] ?? 'blaze',
                    'xg' => $t['x_group'] ?? '', 'xs' => $t['x_store'] ?? '', 'mode' => $t['x_app_mode'] ?? 'default', 'home' => $home,
                ]
            );
            Database::query(
                "INSERT INTO ci_stores (name, platform, api_url, x_group, x_store, x_app_mode, is_home)
                 VALUES (:name, :platform, :url, :xg, :xs, :mode, :home)
                 ON DUPLICATE KEY UPDATE platform=VALUES(platform), api_url=VALUES(api_url),
                   x_group=VALUES(x_group), x_store=VALUES(x_store), x_app_mode=VALUES(x_app_mode), is_home=VALUES(is_home)",
                [
                    'name' => $t['name'], 'platform' => $t['platform'] ?? 'blaze',
                    'url' => $t['api_url'] ?? 'https://ecom-api.blaze.me/api/v1/products',
                    'xg' => $t['x_group'] ?? '', 'xs' => $t['x_store'] ?? '', 'mode' => $t['x_app_mode'] ?? 'default', 'home' => $home,
                ]
            );
        }
    }
}
